version: '3'

services:
  web:
    build: .
    ports:
      - "5500:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - ANSWER_FILE=answers.json
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quiz

volumes:
  postgres_data: